### ISSUE TITLE
Plugin cannot send email

### ISSUE THREAD

**Issue by dvor** [dbf256/teamcity-password-reset-plugin#2]
I've added your plugin to TeamCity, however for some reason it is expecting issues with sending email on password reset. Please note that email notifications are properly configured and work in other cases (when pressing "Test Connection" button or for successful/failing builds).

TeamCity version: 9.1 (build 36973)
Logs from teamcity-server.log:

```
[2016-01-06 16:41:47,185]   INFO -   jetbrains.buildServer.SERVER - 1 user(s) were found for email@iwantto.reset 
[2016-01-06 16:41:47,191]  ERROR -   jetbrains.buildServer.SERVER - Failed to send message, SMTP config is not valid: Port is not set, Host is not set 
```

**Comment by dbf256** [comment]
Hi Dmytro, looks like plugin can't load SMTP config from TC config file. Could you please attach Teamcity main-config.xml (you may remove everything except password reset plugin section and replace all sensitive parameters with dummy values). Also could you please grep Teamcity server log for lines like "Loaded config", "Config is not valid:" and "Config could be not valid:" and add them also. Thanks!

**Comment by dvor** [comment]
Hi @dbf256, sorry, somehow I missed configuration section of README. After configuring smtp parameters in main-config.xml everything works fine.

**Comment by dbf256** [comment]
ok. I have a plan to re-use Teamcity settings without additional configuration (https://github.com/dbf256/teamcity-password-reset-plugin/issues/1), but was not able to complete it yet.
