### ISSUE TITLE
Consider using your own configuration file.

### ISSUE THREAD

**Issue by tmiller** [dbf256/teamcity-password-reset-plugin#3]
Instead of placing your settings in config/main-config.xml. You should consider making your own config file like `config/teamcity-password-reset-plugin.xml` and reading your settings from there. Instead of doing it manually you could also do it like these guys https://github.com/guardian/teamcity-s3-plugin. And have your own settings page and have it write to that file.

**Comment by dbf256** [comment]
Hi, what is the benefit to keep plugin configuration in separate file?
